name: meloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.2.1
  dotted_border: ^2.0.0
  flutter_inappwebview: 6.1.5
  get: 4.7.2
  get_storage: 2.1.1
  flutter_smart_dialog: 4.9.8+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/